name: Publish NuGet Package

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: dotnet restore
        run: |
          dotnet --version
          dotnet restore .


      - name: Add GitHub Packages source
        run: dotnet nuget add source --username ryancody --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/ryancody/index.json"

      - name: Pack
        run: dotnet pack --configuration Release --no-build

      - name: Publish
        run: dotnet nuget push "**/*.nupkg" --source "github" --api-key ${{ secrets.GITHUB_TOKEN }}
